site_name: Acme Docs
nav:
  - Home: index.md
  - Releases:
      - Unreleased:
          - "PR #1": releases/unreleased/1-summary.md
          - "PR #2": releases/unreleased/2-summary.md
  - System:
      - Status: system/docbot-status.md
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
theme:
  name: material
